apiVersion: v1
kind: Pod
metadata:
  name: mnist-train
spec:
  restartPolicy: Never
  containers:
  - name: mnist-train
    image: mnist:train
    command: ['sh', '-c', 'python3 main.py --epoch 1 --save-model']
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "1000Mi"
    volumeMounts:
    - name: model-volume
      mountPath: /app/model
  volumes:
  - name: model-volume
    hostPath:
      path: /mnt
      type: Directory